module Mml
  module Base
    autoload :Maction, "#{__dir__}/base/maction"
    autoload :Maligngroup, "#{__dir__}/base/maligngroup"
    autoload :Malignmark, "#{__dir__}/base/malignmark"
    autoload :Math, "#{__dir__}/base/math"
    autoload :Menclose, "#{__dir__}/base/menclose"
    autoload :Merror, "#{__dir__}/base/merror"
    autoload :Mfenced, "#{__dir__}/base/mfenced"
    autoload :Mfrac, "#{__dir__}/base/mfrac"
    autoload :Mfraction, "#{__dir__}/base/mfraction"
    autoload :Mglyph, "#{__dir__}/base/mglyph"
    autoload :Mi, "#{__dir__}/base/mi"
    autoload :Mlabeledtr, "#{__dir__}/base/mlabeledtr"
    autoload :Mlongdiv, "#{__dir__}/base/mlongdiv"
    autoload :Mmultiscripts, "#{__dir__}/base/mmultiscripts"
    autoload :Mn, "#{__dir__}/base/mn"
    autoload :Mo, "#{__dir__}/base/mo"
    autoload :Mover, "#{__dir__}/base/mover"
    autoload :Mpadded, "#{__dir__}/base/mpadded"
    autoload :Mphantom, "#{__dir__}/base/mphantom"
    autoload :Mprescripts, "#{__dir__}/base/mprescripts"
    autoload :Mroot, "#{__dir__}/base/mroot"
    autoload :Mrow, "#{__dir__}/base/mrow"
    autoload :Ms, "#{__dir__}/base/ms"
    autoload :Mscarries, "#{__dir__}/base/mscarries"
    autoload :Mscarry, "#{__dir__}/base/mscarry"
    autoload :Msgroup, "#{__dir__}/base/msgroup"
    autoload :Msline, "#{__dir__}/base/msline"
    autoload :Mspace, "#{__dir__}/base/mspace"
    autoload :Msqrt, "#{__dir__}/base/msqrt"
    autoload :Msrow, "#{__dir__}/base/msrow"
    autoload :Mstack, "#{__dir__}/base/mstack"
    autoload :Mstyle, "#{__dir__}/base/mstyle"
    autoload :Msub, "#{__dir__}/base/msub"
    autoload :Msubsup, "#{__dir__}/base/msubsup"
    autoload :Msup, "#{__dir__}/base/msup"
    autoload :Mtable, "#{__dir__}/base/mtable"
    autoload :Mtd, "#{__dir__}/base/mtd"
    autoload :Mtext, "#{__dir__}/base/mtext"
    autoload :Mtr, "#{__dir__}/base/mtr"
    autoload :Munder, "#{__dir__}/base/munder"
    autoload :Munderover, "#{__dir__}/base/munderover"
    autoload :None, "#{__dir__}/base/none"
    autoload :Semantics, "#{__dir__}/base/semantics"
    autoload :CommonAttributes, "#{__dir__}/base/common_attributes"
    autoload :UniversalPresentationAttributes,
             "#{__dir__}/base/universal_presentation_attributes"
    autoload :V3Common, "#{__dir__}/base/v3_common"
    autoload :V3PresentationAttributes,
             "#{__dir__}/base/v3_presentation_attributes"
    autoload :V4OnlyAttributes,
             "#{__dir__}/base/universal_presentation_attributes"
    autoload :V4Attributes, "#{__dir__}/base/v4_attributes"
    autoload :DeprecatedFontAttributes,
             "#{__dir__}/base/deprecated_font_attributes"
    autoload :V3Only, "#{__dir__}/base/v3_only"
    autoload :Content, "#{__dir__}/base/content_loader"
    autoload :Declare, "#{__dir__}/base/content/declare"
    autoload :Share, "#{__dir__}/base/content/share"
  end
end
