# frozen_string_literal: true

require "lutaml/model"

module Mml
  module V3
    extend Mml::VersionedParser

    autoload :Configuration, "mml/v3/configuration"
    autoload :Namespace,     "mml/v3/namespace"
    autoload :CommonElements, "mml/v3/common_elements"

    # Presentation elements
    autoload :Maction,       "mml/v3/maction"
    autoload :Maligngroup,   "mml/v3/maligngroup"
    autoload :Malignmark,    "mml/v3/malignmark"
    autoload :Menclose,      "mml/v3/menclose"
    autoload :Merror,        "mml/v3/merror"
    autoload :Mfenced,       "mml/v3/mfenced"
    autoload :Mfrac,         "mml/v3/mfrac"
    autoload :Mfraction,     "mml/v3/mfraction"
    autoload :Mglyph,        "mml/v3/mglyph"
    autoload :Mi,            "mml/v3/mi"
    autoload :Mlongdiv,      "mml/v3/mlongdiv"
    autoload :Mn,            "mml/v3/mn"
    autoload :Mo,            "mml/v3/mo"
    autoload :Mover,         "mml/v3/mover"
    autoload :Mpadded,       "mml/v3/mpadded"
    autoload :Mphantom,      "mml/v3/mphantom"
    autoload :Mprescripts,   "mml/v3/mprescripts"
    autoload :Mroot,         "mml/v3/mroot"
    autoload :Mrow,          "mml/v3/mrow"
    autoload :Ms,            "mml/v3/ms"
    autoload :Mscarries,     "mml/v3/mscarries"
    autoload :Mscarry,       "mml/v3/mscarry"
    autoload :Msgroup,       "mml/v3/msgroup"
    autoload :Msline,        "mml/v3/msline"
    autoload :Mspace,        "mml/v3/mspace"
    autoload :Msqrt,         "mml/v3/msqrt"
    autoload :Msrow,         "mml/v3/msrow"
    autoload :Mstack,        "mml/v3/mstack"
    autoload :Mstyle,        "mml/v3/mstyle"
    autoload :Msub,          "mml/v3/msub"
    autoload :Msubsup,       "mml/v3/msubsup"
    autoload :Msup,          "mml/v3/msup"
    autoload :Mtd,           "mml/v3/mtd"
    autoload :Mtable,        "mml/v3/mtable"
    autoload :Mtext,         "mml/v3/mtext"
    autoload :Mtr,           "mml/v3/mtr"
    autoload :Mlabeledtr,    "mml/v3/mlabeledtr"
    autoload :Munder,        "mml/v3/munder"
    autoload :Munderover,    "mml/v3/munderover"
    autoload :Mmultiscripts, "mml/v3/mmultiscripts"
    autoload :None,          "mml/v3/none"
    autoload :Semantics,     "mml/v3/semantics"
    autoload :Math,          "mml/v3/math"

    # Content elements
    autoload :Apply,         "mml/v3/apply"
    autoload :Cbytes,        "mml/v3/cbytes"
    autoload :Cerror,        "mml/v3/cerror"
    autoload :Cs,            "mml/v3/cs"
    autoload :Ci,            "mml/v3/ci"
    autoload :Cn,            "mml/v3/cn"
    autoload :Csymbol,       "mml/v3/csymbol"
    autoload :AnnotationXml, "mml/v3/annotation_xml"
    autoload :Annotation,    "mml/v3/annotation"
    autoload :Bind,          "mml/v3/bind"

    # MathML 2 compatibility (deprecated in V3)
    autoload :Fn,            "mml/v3/deprecated_content"
    autoload :Reln,          "mml/v3/deprecated_content"
    autoload :Declare,       "mml/v3/deprecated_content"
    autoload :Share,         "mml/v3/deprecated_content"

    # Constructs (shared file defines multiple classes)
    autoload :Bvar,          "mml/v3/constructs"
    autoload :Condition,     "mml/v3/constructs"
    autoload :Interval,      "mml/v3/constructs"
    autoload :Lambda,        "mml/v3/constructs"
    autoload :Inverse,       "mml/v3/constructs"
    autoload :Degree,        "mml/v3/constructs"
    autoload :Piecewise,     "mml/v3/constructs"
    autoload :Piece,         "mml/v3/constructs"
    autoload :Otherwise,     "mml/v3/constructs"
    autoload :Sep,           "mml/v3/constructs"

    # Arith batch
    autoload :Abs,           "mml/v3/arith"
    autoload :Conjugate,     "mml/v3/arith"
    autoload :Arg,           "mml/v3/arith"
    autoload :Real,          "mml/v3/arith"
    autoload :Imaginary,     "mml/v3/arith"
    autoload :Floor,         "mml/v3/arith"
    autoload :Ceiling,       "mml/v3/arith"
    autoload :Quotient,      "mml/v3/arith"
    autoload :Divide,        "mml/v3/arith"
    autoload :Rem,           "mml/v3/arith"
    autoload :Minus,         "mml/v3/arith"
    autoload :Plus,          "mml/v3/arith"
    autoload :Times,         "mml/v3/arith"
    autoload :Power,         "mml/v3/arith"
    autoload :Root,          "mml/v3/arith"
    autoload :Max,           "mml/v3/arith"
    autoload :Min,           "mml/v3/arith"
    autoload :Gcd,           "mml/v3/arith"
    autoload :Lcm,           "mml/v3/arith"
    autoload :Sum,           "mml/v3/arith"
    autoload :Product,       "mml/v3/arith"
    autoload :Factorial,     "mml/v3/arith"

    # Logic batch
    autoload :And,           "mml/v3/logic"
    autoload :Or,            "mml/v3/logic"
    autoload :Xor,           "mml/v3/logic"
    autoload :Not,           "mml/v3/logic"
    autoload :Implies,       "mml/v3/logic"
    autoload :Forall,        "mml/v3/logic"
    autoload :Exists,        "mml/v3/logic"

    # Relations batch
    autoload :Eq,            "mml/v3/relations"
    autoload :Neq,           "mml/v3/relations"
    autoload :Lt,            "mml/v3/relations"
    autoload :Gt,            "mml/v3/relations"
    autoload :Leq,           "mml/v3/relations"
    autoload :Geq,           "mml/v3/relations"
    autoload :Equivalent,    "mml/v3/relations"
    autoload :Approx,        "mml/v3/relations"
    autoload :Factorof,      "mml/v3/relations"

    # Sets batch
    autoload :Set,           "mml/v3/sets"
    autoload :Mlist, "mml/v3/sets"
    autoload :Union,         "mml/v3/sets"
    autoload :Intersect,     "mml/v3/sets"
    autoload :In,            "mml/v3/sets"
    autoload :Notin,         "mml/v3/sets"
    autoload :Notsubset,     "mml/v3/sets"
    autoload :Notprsubset,   "mml/v3/sets"
    autoload :Subset,        "mml/v3/sets"
    autoload :Prsubset,      "mml/v3/sets"
    autoload :Setdiff,       "mml/v3/sets"
    autoload :Card,          "mml/v3/sets"
    autoload :Cartesianproduct, "mml/v3/sets"

    # Calculus batch
    autoload :Diff,          "mml/v3/calculus"
    autoload :Partialdiff,   "mml/v3/calculus"
    autoload :Int,           "mml/v3/calculus"
    autoload :Limit,         "mml/v3/calculus"
    autoload :Lowlimit,      "mml/v3/calculus"
    autoload :Tendsto,       "mml/v3/calculus"
    autoload :Uplimit,       "mml/v3/calculus"

    # Vector calculus batch
    autoload :Divergence,    "mml/v3/vector_calculus"
    autoload :Grad,          "mml/v3/vector_calculus"
    autoload :Curl,          "mml/v3/vector_calculus"
    autoload :Laplacian,     "mml/v3/vector_calculus"

    # Functions batch
    autoload :Compose,       "mml/v3/functions"
    autoload :Domain,        "mml/v3/functions"
    autoload :Codomain,      "mml/v3/functions"
    autoload :Image,         "mml/v3/functions"
    autoload :Ident,         "mml/v3/functions"

    # Elementary functions batch
    autoload :Sin,           "mml/v3/elementary_functions"
    autoload :Cos,           "mml/v3/elementary_functions"
    autoload :Tan,           "mml/v3/elementary_functions"
    autoload :Sec,           "mml/v3/elementary_functions"
    autoload :Csc,           "mml/v3/elementary_functions"
    autoload :Cot,           "mml/v3/elementary_functions"
    autoload :Sinh,          "mml/v3/elementary_functions"
    autoload :Cosh,          "mml/v3/elementary_functions"
    autoload :Tanh,          "mml/v3/elementary_functions"
    autoload :Sech,          "mml/v3/elementary_functions"
    autoload :Csch,          "mml/v3/elementary_functions"
    autoload :Coth,          "mml/v3/elementary_functions"
    autoload :Arcsin,        "mml/v3/elementary_functions"
    autoload :Arccos,        "mml/v3/elementary_functions"
    autoload :Arctan,        "mml/v3/elementary_functions"
    autoload :Arcsec,        "mml/v3/elementary_functions"
    autoload :Arccsc,        "mml/v3/elementary_functions"
    autoload :Arccot,        "mml/v3/elementary_functions"
    autoload :Arcsinh,       "mml/v3/elementary_functions"
    autoload :Arccosh,       "mml/v3/elementary_functions"
    autoload :Arctanh,       "mml/v3/elementary_functions"
    autoload :Arcsech,       "mml/v3/elementary_functions"
    autoload :Arccsch,       "mml/v3/elementary_functions"
    autoload :Arccoth,       "mml/v3/elementary_functions"
    autoload :Exp,           "mml/v3/elementary_functions"
    autoload :Ln,            "mml/v3/elementary_functions"
    autoload :Log,           "mml/v3/elementary_functions"

    # Constants batch
    autoload :Integers,      "mml/v3/constants"
    autoload :Reals,         "mml/v3/constants"
    autoload :Rationals,     "mml/v3/constants"
    autoload :Naturalnumbers, "mml/v3/constants"
    autoload :Complexes,     "mml/v3/constants"
    autoload :Primes,        "mml/v3/constants"
    autoload :Exponentiale,  "mml/v3/constants"
    autoload :Imaginaryi,    "mml/v3/constants"
    autoload :Notanumber,    "mml/v3/constants"
    autoload :Mtrue,         "mml/v3/constants" # rubocop:disable Lint/BooleanSymbol
    autoload :Mfalse,        "mml/v3/constants" # rubocop:disable Lint/BooleanSymbol
    autoload :Emptyset,      "mml/v3/constants"
    autoload :Pi,            "mml/v3/constants"
    autoload :Eulergamma,    "mml/v3/constants"
    autoload :Infinity,      "mml/v3/constants"

    # Linear algebra batch
    autoload :Vector,        "mml/v3/linear_algebra"
    autoload :Matrix,        "mml/v3/linear_algebra"
    autoload :Matrixrow,     "mml/v3/linear_algebra"
    autoload :Determinant,   "mml/v3/linear_algebra"
    autoload :Transpose,     "mml/v3/linear_algebra"
    autoload :Selector,      "mml/v3/linear_algebra"
    autoload :Vectorproduct, "mml/v3/linear_algebra"
    autoload :Scalarproduct, "mml/v3/linear_algebra"
    autoload :Outerproduct,  "mml/v3/linear_algebra"

    # Statistics batch
    autoload :Mean,          "mml/v3/statistics"
    autoload :Sdev,          "mml/v3/statistics"
    autoload :Variance,      "mml/v3/statistics"
    autoload :Median,        "mml/v3/statistics"
    autoload :Mode,          "mml/v3/statistics"
    autoload :Moment,        "mml/v3/statistics"
    autoload :Momentabout,   "mml/v3/statistics"
  end
end
