# frozen_string_literal: true

module Mml
  module Base
    # Content MathML elements autoloader
    module Content
      autoload :Cn, "#{__dir__}/content/cn"
      autoload :Ci, "#{__dir__}/content/ci"
      autoload :Csymbol, "#{__dir__}/content/csymbol"
      autoload :Cbytes, "#{__dir__}/content/cbytes"
      autoload :Cs, "#{__dir__}/content/cs"
      autoload :Cerror, "#{__dir__}/content/cerror"
      autoload :Apply, "#{__dir__}/content/apply"
      autoload :Semantics, "#{__dir__}/content/semantics"
      autoload :Annotation, "#{__dir__}/content/annotation"
      autoload :AnnotationXml, "#{__dir__}/content/annotation_xml"

      # Constructs
      autoload :Bvar, "#{__dir__}/content/bvar"
      autoload :Bind, "#{__dir__}/content/bind"
      autoload :Condition, "#{__dir__}/content/condition"
      autoload :Interval, "#{__dir__}/content/interval"
      autoload :Lambda, "#{__dir__}/content/lambda"
      autoload :Inverse, "#{__dir__}/content/inverse"
      autoload :Degree, "#{__dir__}/content/degree"
      autoload :Piecewise, "#{__dir__}/content/piecewise"
      autoload :Piece, "#{__dir__}/content/piece"
      autoload :Otherwise, "#{__dir__}/content/otherwise"
      autoload :Sep, "#{__dir__}/content/sep"

      # Arithmetic (all defined in arith.rb)
      autoload :Arith, "#{__dir__}/content/arith"
      autoload :Abs, "#{__dir__}/content/arith"
      autoload :Conjugate, "#{__dir__}/content/arith"
      autoload :Arg, "#{__dir__}/content/arith"
      autoload :Real, "#{__dir__}/content/arith"
      autoload :Imaginary, "#{__dir__}/content/arith"
      autoload :Floor, "#{__dir__}/content/arith"
      autoload :Ceiling, "#{__dir__}/content/arith"
      autoload :Quotient, "#{__dir__}/content/arith"
      autoload :Divide, "#{__dir__}/content/arith"
      autoload :Rem, "#{__dir__}/content/arith"
      autoload :Minus, "#{__dir__}/content/arith"
      autoload :Plus, "#{__dir__}/content/arith"
      autoload :Times, "#{__dir__}/content/arith"
      autoload :Power, "#{__dir__}/content/arith"
      autoload :Root, "#{__dir__}/content/arith"
      autoload :Max, "#{__dir__}/content/arith"
      autoload :Min, "#{__dir__}/content/arith"
      autoload :Gcd, "#{__dir__}/content/arith"
      autoload :Lcm, "#{__dir__}/content/arith"
      autoload :Sum, "#{__dir__}/content/arith"
      autoload :Product, "#{__dir__}/content/arith"
      autoload :Factorial, "#{__dir__}/content/arith"

      # Logic (all defined in logic.rb)
      autoload :Logic, "#{__dir__}/content/logic"
      autoload :And, "#{__dir__}/content/logic"
      autoload :Or, "#{__dir__}/content/logic"
      autoload :Xor, "#{__dir__}/content/logic"
      autoload :Not, "#{__dir__}/content/logic"
      autoload :Implies, "#{__dir__}/content/logic"
      autoload :Forall, "#{__dir__}/content/logic"
      autoload :Exists, "#{__dir__}/content/logic"

      # Relations (all defined in relations.rb)
      autoload :Relations, "#{__dir__}/content/relations"
      autoload :Eq, "#{__dir__}/content/relations"
      autoload :Neq, "#{__dir__}/content/relations"
      autoload :Lt, "#{__dir__}/content/relations"
      autoload :Gt, "#{__dir__}/content/relations"
      autoload :Leq, "#{__dir__}/content/relations"
      autoload :Geq, "#{__dir__}/content/relations"
      autoload :Equivalent, "#{__dir__}/content/relations"
      autoload :Approx, "#{__dir__}/content/relations"
      autoload :Factorof, "#{__dir__}/content/relations"

      # Sets (all defined in sets.rb)
      autoload :Sets, "#{__dir__}/content/sets"
      autoload :Set, "#{__dir__}/content/sets"
      autoload :Union, "#{__dir__}/content/sets"
      autoload :Intersect, "#{__dir__}/content/sets"
      autoload :In, "#{__dir__}/content/sets"
      autoload :Notin, "#{__dir__}/content/sets"
      autoload :Subset, "#{__dir__}/content/sets"
      autoload :Prsubset, "#{__dir__}/content/sets"
      autoload :Notsubset, "#{__dir__}/content/sets"
      autoload :Notprsubset, "#{__dir__}/content/sets"
      autoload :Setdiff, "#{__dir__}/content/sets"
      autoload :Card, "#{__dir__}/content/sets"
      autoload :Cartesianproduct, "#{__dir__}/content/sets"

      # Calculus (all defined in calculus.rb)
      autoload :Calculus, "#{__dir__}/content/calculus"
      autoload :Int, "#{__dir__}/content/calculus"
      autoload :Diff, "#{__dir__}/content/calculus"
      autoload :Partialdiff, "#{__dir__}/content/calculus"
      autoload :Limit, "#{__dir__}/content/calculus"
      autoload :Lowlimit, "#{__dir__}/content/calculus"
      autoload :Uplimit, "#{__dir__}/content/calculus"
      autoload :Tendsto, "#{__dir__}/content/calculus"

      # Functions (all defined in functions.rb)
      autoload :Functions, "#{__dir__}/content/functions"
      autoload :Compose, "#{__dir__}/content/functions"
      autoload :Domain, "#{__dir__}/content/functions"
      autoload :Codomain, "#{__dir__}/content/functions"
      autoload :Image, "#{__dir__}/content/functions"
      autoload :Ident, "#{__dir__}/content/functions"
      autoload :Domainofapplication, "#{__dir__}/content/functions"
      autoload :Fn, "#{__dir__}/content/fn"
      autoload :Reln, "#{__dir__}/content/reln"
      autoload :Declare, "#{__dir__}/content/declare"
      autoload :Share, "#{__dir__}/content/share"

      # Elementary functions (all defined in elementary_functions.rb)
      autoload :ElementaryFunctions, "#{__dir__}/content/elementary_functions"
      autoload :Exp, "#{__dir__}/content/elementary_functions"
      autoload :Ln, "#{__dir__}/content/elementary_functions"
      autoload :Log, "#{__dir__}/content/elementary_functions"
      autoload :Logbase, "#{__dir__}/content/elementary_functions"
      autoload :Sin, "#{__dir__}/content/elementary_functions"
      autoload :Cos, "#{__dir__}/content/elementary_functions"
      autoload :Tan, "#{__dir__}/content/elementary_functions"
      autoload :Sec, "#{__dir__}/content/elementary_functions"
      autoload :Csc, "#{__dir__}/content/elementary_functions"
      autoload :Cot, "#{__dir__}/content/elementary_functions"
      autoload :Arcsin, "#{__dir__}/content/elementary_functions"
      autoload :Arccos, "#{__dir__}/content/elementary_functions"
      autoload :Arctan, "#{__dir__}/content/elementary_functions"
      autoload :Arccot, "#{__dir__}/content/elementary_functions"
      autoload :Arccsc, "#{__dir__}/content/elementary_functions"
      autoload :Arcsec, "#{__dir__}/content/elementary_functions"
      autoload :Sinh, "#{__dir__}/content/elementary_functions"
      autoload :Cosh, "#{__dir__}/content/elementary_functions"
      autoload :Tanh, "#{__dir__}/content/elementary_functions"
      autoload :Sech, "#{__dir__}/content/elementary_functions"
      autoload :Csch, "#{__dir__}/content/elementary_functions"
      autoload :Coth, "#{__dir__}/content/elementary_functions"
      autoload :Arcsinh, "#{__dir__}/content/elementary_functions"
      autoload :Arccosh, "#{__dir__}/content/elementary_functions"
      autoload :Arctanh, "#{__dir__}/content/elementary_functions"
      autoload :Arccoth, "#{__dir__}/content/elementary_functions"
      autoload :Arccsch, "#{__dir__}/content/elementary_functions"
      autoload :Arcsech, "#{__dir__}/content/elementary_functions"

      # Constants (all defined in constants.rb)
      autoload :Constants, "#{__dir__}/content/constants"
      autoload :Naturalnumbers, "#{__dir__}/content/constants"
      autoload :Primes, "#{__dir__}/content/constants"
      autoload :Integers, "#{__dir__}/content/constants"
      autoload :Rationals, "#{__dir__}/content/constants"
      autoload :Reals, "#{__dir__}/content/constants"
      autoload :Complexes, "#{__dir__}/content/constants"
      autoload :Emptyset, "#{__dir__}/content/constants"
      autoload :Exponentiale, "#{__dir__}/content/constants"
      autoload :Imaginaryi, "#{__dir__}/content/constants"
      autoload :Pi, "#{__dir__}/content/constants"
      autoload :Eulergamma, "#{__dir__}/content/constants"
      autoload :True, "#{__dir__}/content/constants"
      autoload :False, "#{__dir__}/content/constants"
      autoload :Infinity, "#{__dir__}/content/constants"
      autoload :Notanumber, "#{__dir__}/content/constants"

      # Linear algebra (all defined in linear_algebra.rb)
      autoload :LinearAlgebra, "#{__dir__}/content/linear_algebra"
      autoload :Vector, "#{__dir__}/content/linear_algebra"
      autoload :Matrix, "#{__dir__}/content/linear_algebra"
      autoload :Matrixrow, "#{__dir__}/content/linear_algebra"
      autoload :Determinant, "#{__dir__}/content/linear_algebra"
      autoload :Transpose, "#{__dir__}/content/linear_algebra"
      autoload :Selector, "#{__dir__}/content/linear_algebra"
      autoload :Vectorproduct, "#{__dir__}/content/linear_algebra"
      autoload :Scalarproduct, "#{__dir__}/content/linear_algebra"
      autoload :Outerproduct, "#{__dir__}/content/linear_algebra"

      # Vector calculus (all defined in vector_calculus.rb)
      autoload :VectorCalculus, "#{__dir__}/content/vector_calculus"
      autoload :Divergence, "#{__dir__}/content/vector_calculus"
      autoload :Grad, "#{__dir__}/content/vector_calculus"
      autoload :Curl, "#{__dir__}/content/vector_calculus"
      autoload :Laplacian, "#{__dir__}/content/vector_calculus"

      # Statistics (all defined in statistics.rb)
      autoload :Statistics, "#{__dir__}/content/statistics"
      autoload :Mean, "#{__dir__}/content/statistics"
      autoload :Sdev, "#{__dir__}/content/statistics"
      autoload :Variance, "#{__dir__}/content/statistics"
      autoload :Median, "#{__dir__}/content/statistics"
      autoload :Mode, "#{__dir__}/content/statistics"
      autoload :Moment, "#{__dir__}/content/statistics"
      autoload :Momentabout, "#{__dir__}/content/statistics"
    end
  end
end
