#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates lib/mml/opal.rb by scanning lib/mml/**/*.rb.
# Re-run after adding new model files.

require "pathname"

ROOT = File.expand_path("..", __dir__)
LIB_MML = File.join(ROOT, "lib", "mml")
OUTPUT = File.join(LIB_MML, "opal.rb")

files = Dir.glob(File.join(LIB_MML, "**", "*.rb")).sort.map do |path|
  path.sub(%r{^#{ROOT}/lib/}, "").sub(/\.rb\z/, "")
end

header = <<~HEADER
  # frozen_string_literal: true

  # Opal entry point for mml.
  #
  # Under MRI, lib/mml.rb uses autoload for lazy loading. Under Opal,
  # autoload does not lazy-execute, so this boot file eager-requires
  # every entry point. Consumers add `-r mml/opal` to their Opal
  # compile command.
  #
  # AUTO-GENERATED by `bundle exec ruby scripts/generate-opal-boot.rb`.
  # Don't hand-edit — re-run the generator after adding new model files.

  require "lutaml/model"

HEADER

body = files.map { |f| %(require "#{f}") }.join("\n")
File.write(OUTPUT, "#{header}#{body}\n")
warn "wrote #{OUTPUT} with #{files.length} requires"